
CREATE TABLE TB_INFO(
    INFO_NO NUMBER(3) NOT NULL 
    ,PC_NO VARCHAR2(10) UNIQUE NOT NULL 
    ,NM VARCHAR2(20)
    ,EMAIL VARCHAR2(50)
    ,HOBBY VARCHAR2(1000)
    ,MBTI VARCHAR2(4)
    );
  

SELECT INFO_NO AS 번호, PC_NO AS PC번호, NM AS 이름, EMAIL AS 이메일주소, HOBBY AS 취미, MBTI AS MBTI
FROM TB_INFO;
